version: "3"
services:
  db:
    image: postgres:9.6
    container_name: pg-jbsrm
    ports:
    - "5336:5432"
    environment:
      POSTGRES_PASSWORD: 123qwe123
      POSTGRES_USER: admin
      POSTGRES_DB: jbsrm

  jbsrb-static-server:
    image: "jbsrm-static-server:latest"
    container_name: jbsrm-server
    ports:
      - "50031:80"
    links:
      - jbsrb-rest-server

  jbsrb-rest-server:
    image: "jbsrm-rest-server:latest"
    container_name: jbsrb-rest-server
    depends_on:
      - db
    ports:
      - "8080:8080"
