spring:
  datasource:
    url: jdbc:postgresql://db:5432/jbsrm
#    url: jdbc:postgresql://localhost:5446/jbsrm
    username: admin
    password: 123qwe123
  resources:
    chain:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        cache.use_second_level_cache: false
        cache.use_query_cache: false
        generate_statistics: false
        temp.use_jdbc_metadata_defaults: false
        jdbc.lob.non_contextual_creation: true
        jdbc.batch_size: 500
        order_inserts: true
        batch_fetch_style: DYNAMIC
        show_sql: true
#  liquibase.change-log: classpath:/db/changelog/liquibase-changelog.xml
#  logging.level.liquibase: INFO

management:
  security:
    enabled: true

server:
  port: 8080

jbsrm.app.jwtSecret: jwtSecretKey
jbsrm.app.jwtExpiration: 86400
jbsrm.app.registration_secret: registrationSecretKey
jbsrm.app.registration_receiver: http://localhost:8080/user/register/
jbsrm.mail_sender:
  host: smtp.gmail.com
  port: 587
  username: jbsrm.mail@gmail.com
  password: 123qwe234

#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE